# Generated by Django 2.1.3 on 2018-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpster', '0002_auto_20181201_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
