# Generated by Django 2.1.3 on 2018-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpster', '0003_hook_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='profile_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
